# Generated by Django 5.2 on 2025-07-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=225)),
                ('apellidos', models.CharField(max_length=225)),
                ('cedula', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=225)),
                ('celular', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha_nacimiento')),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=28, verbose_name='estado civil')),
                ('tipo_sangre', models.CharField(max_length=3, null=True, verbose_name='tipo de sangre')),
                ('apellido_espos', models.CharField(max_length=225)),
                ('canton', models.CharField(max_length=1000)),
                ('correo', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
