# Generated by Django 5.2 on 2025-07-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_pacientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
