# Generated by Django 5.2 on 2025-07-05 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225, verbose_name='nombre de la especialidad')),
                ('descripcion', models.TextField(verbose_name='descripcion de la especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=225)),
                ('apellidos', models.CharField(max_length=225)),
                ('cedula', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField(verbose_name='fecha dela cita')),
                ('hora_cita', models.TimeField(verbose_name='hora de la cita')),
                ('medico', models.CharField(max_length=50, verbose_name='nombre del medico')),
                ('especilidad', models.CharField(max_length=225, verbose_name='nombre de la especialidad')),
                ('Pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.pacientes')),
            ],
        ),
    ]
