# Generated by Django 5.2 on 2025-07-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0004_especialidades_medicos_citas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='especilidad',
            new_name='especialidad',
        ),
        migrations.RenameField(
            model_name='citas',
            old_name='Pacientes',
            new_name='paciente',
        ),
        migrations.RemoveField(
            model_name='especialidades',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
