# Generated by Django 5.2 on 2025-07-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0005_rename_especilidad_citas_especialidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='nombre',
            new_name='especialidad_id',
        ),
    ]
