# Generated by Django 5.2 on 2025-07-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0007_rename_especialidad_id_especialidades_nombre_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.especialidades'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='fecha_cita',
            field=models.DateField(verbose_name='fecha de la cita'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='medico',
            field=models.CharField(max_length=50, verbose_name='nombre del médico'),
        ),
    ]
