# Generated by Django 5.2 on 2025-07-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0008_alter_citas_especialidad_alter_citas_fecha_cita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='especialidad',
        ),
        migrations.DeleteModel(
            name='Especialidades',
        ),
    ]
