# Generated by Django 5.2 on 2025-07-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0010_especialidades_citas_especialidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidades',
            new_name='Especialidad',
        ),
    ]
