# Generated by Django 5.2 on 2025-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0011_rename_especialidades_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la especialidad'),
        ),
    ]
