# Generated by Django 5.2 on 2025-07-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0012_alter_especialidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(choices=[('fisioterapia', 'Fisioterapia'), ('neumologia', 'Neumología'), ('psicologia_clinica', 'Psicología Clínica'), ('odontologia', 'Odontología'), ('traumatologia_ortopedia', 'Traumatología y Ortopedia'), ('nutricion_dietetica_estetica', 'Nutrición Dietética y Estética'), ('fonoaudiologia', 'Fonoaudiología'), ('ginecologia_obstetricia', 'Ginecología y Obstetricia'), ('medicina_general_integral', 'Medicina General Integral')], max_length=50, unique=True),
        ),
    ]
