# Generated by Django 5.2 on 2025-07-16 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0013_alter_especialidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.medicos', verbose_name='Médico'),
        ),
    ]
